import { inject, Injectable } from '@angular/core';
import { HttpClient } from '@angular/common/http';
import { Observable, of } from 'rxjs';
import { Organization } from './organization';
import { environment } from '../../../environments/environment';
import { Address } from '../../shared/model/address';

@Injectable({
  providedIn: 'root',
})
export class OrganizationsService {
  public apiUrl = environment.apiUrl;
  private http = inject(HttpClient);

  getAll(): Observable<Organization[]> {
    return this.http.get<Organization[]>(this.apiUrl + '/organizations');
  }

  getById(id: number): Observable<Organization> {
    //return this.http.get<Organization>(this.apiUrl + '/organizations/' + id);
    return of({
      id: 1,
      name: 'Freiwillige Feuerwehr Grafenrheinfeld',
      notes: 'Generated by Skillflow AI',
      logo: 'https://www.skillflow.ai/wp-content/uploads/2021/03/logo-skillflow-ai-1.png',
      created: new Date(),
      email: 'ffw@grafenrheinfeld.de',
      phone: '09723/938231',
      address: {
        street: 'Hohe Heide',
        number: '4',
        zip: '97506',
        city: 'Grafenrheinnfeld',
      } as Address,
      website: 'https://www.feuerwehr-grafenrheinfeld.de',
    } as Organization);
  }
}
